import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/custom/Navbar";
import Footer from "@/components/custom/Footer";
import Preloader from "@/components/custom/Preloader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isOnloginPage =
    typeof window !== "undefined" && window.location.pathname === "/login";
  const isFirstLoad =
    typeof window !== "undefined" &&
    window.performance &&
    window.performance.navigation.type === 1;

  // Show Navbar and Footer only if not on login page and not first load
  // const showNavbarAndFooter = !isOnloginPage && !isFirstLoad;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {isFirstLoad && <Preloader />}

        {isOnloginPage && <Navbar />}

        {children}
        {isOnloginPage && <Footer />}
      </body>
    </html>
  );
}
